spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tsso?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&amp&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.aliyun.com
    username: test@aliyun
    password: test@aliyun
    default-encoding: UTF-8
    fromMail.addr: olcow.com@aliyun.com
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    # 服务商一半会关闭常用发送邮件端口 所以要用安全特殊发送端口
    port: 465
# 打印所有dao层执行的sql的log 上线时请删除
logging:
  level:
    com.olcow.tsso.dao: debug
#加密密钥
PublicKey: 123456